# Generated by Django 4.0.5 on 2022-07-31 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Total_Staff', models.IntegerField()),
            ],
            options={
                'db_table': 'Dept',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Phone_num', models.BigIntegerField()),
                ('esta_year', models.DateField()),
            ],
            options={
                'db_table': 'Hospital',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('hospi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HSPTL.hospital')),
            ],
            options={
                'db_table': 'Owner',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('No_of_Doctor', models.IntegerField()),
                ('speciality', models.CharField(max_length=100)),
                ('department', models.ManyToManyField(to='HSPTL.department')),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='hospi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HSPTL.hospital'),
        ),
    ]
